# Git pre-commit hooks, see https://pre-commit.com

default_language_version:
  golang: 1.17.5

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: local
    hooks:
      - id: format
        name: format
        entry: "gofmt -l -w"
        language: system
        types: [go]
